/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminAiDrawer: typeof import('./src/components/admin/AdminAiDrawer.vue')['default']
    AdminProfileDrawer: typeof import('./src/components/admin/AdminProfileDrawer.vue')['default']
    AppNotifier: typeof import('./src/components/AppNotifier.vue')['default']
    AppPageHeader: typeof import('./src/components/AppPageHeader.vue')['default']
    BaseBatchToolbar: typeof import('./src/components/BaseBatchToolbar.vue')['default']
    BaseDrawer: typeof import('./src/components/BaseDrawer.vue')['default']
    BaseListToolbar: typeof import('./src/components/BaseListToolbar.vue')['default']
    BaseMoreMenu: typeof import('./src/components/BaseMoreMenu.vue')['default']
    BasePagination: typeof import('./src/components/BasePagination.vue')['default']
    BulkSkuDialog: typeof import('./src/components/products/BulkSkuDialog.vue')['default']
    CustomerDetailDrawer: typeof import('./src/components/users/CustomerDetailDrawer.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ImageUploadField: typeof import('./src/components/shared/ImageUploadField.vue')['default']
    ListSummary: typeof import('./src/components/shared/ListSummary.vue')['default']
    ProductEditorDialog: typeof import('./src/components/products/ProductEditorDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShipOrderDialog: typeof import('./src/components/orders/ShipOrderDialog.vue')['default']
    SkuEditorDialog: typeof import('./src/components/products/SkuEditorDialog.vue')['default']
    StatusTag: typeof import('./src/components/shared/StatusTag.vue')['default']
    StockLogDrawer: typeof import('./src/components/products/StockLogDrawer.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
